// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPage.Data;

namespace RazorPage.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("RazorPage.Data.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "School #1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "School #2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "School #3"
                        });
                });

            modelBuilder.Entity("RazorPage.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User1",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "User2",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "User3",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "User4",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "User5",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "User6",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "User7",
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "User8",
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "User9",
                            SchoolId = 3
                        });
                });

            modelBuilder.Entity("RazorPage.Data.Student", b =>
                {
                    b.HasOne("RazorPage.Data.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });
#pragma warning restore 612, 618
        }
    }
}
