// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoranAdmin.Data;

namespace RestoranAdmin.Data.Migrations
{
    [DbContext(typeof(RestoranDbContext))]
    [Migration("20210408174130_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ADONETDemoFramework.Models.ClientTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientTables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Table 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Table 2"
                        });
                });

            modelBuilder.Entity("ADONETDemoFramework.Models.ClientTableWaiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientTableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaiterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientTableId");

                    b.HasIndex("WaiterId");

                    b.ToTable("ClientTableWaiters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientTableId = 1,
                            WaiterId = 1
                        });
                });

            modelBuilder.Entity("ADONETDemoFramework.Models.FoodItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("[Name] +  [Price]");

                    b.Property<double>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(9.9900000000000002);

                    b.HasKey("Name", "Id")
                        .HasName("myPrimaryKey");

                    b.ToTable("FoodItem");
                });

            modelBuilder.Entity("ADONETDemoFramework.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientTableId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(9, 2)
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("WaiterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientTableId");

                    b.ToTable("Order");

                    b
                        .HasComment("Замовлення");
                });

            modelBuilder.Entity("ADONETDemoFramework.Models.OrderItem", b =>
                {
                    b.Property<string>("PK")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Price");

                    b.HasKey("PK");

                    b.HasIndex("FoodItemName", "FoodItemId1");

                    b.ToTable("order_item", "ddd");
                });

            modelBuilder.Entity("ADONETDemoFramework.Models.Waiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Офіціант", "mybase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Іван",
                            Password = "1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Piter",
                            Password = "2"
                        });
                });

            modelBuilder.Entity("ADONETDemoFramework.Models.ClientTableWaiter", b =>
                {
                    b.HasOne("ADONETDemoFramework.Models.ClientTable", "ClientTable")
                        .WithMany()
                        .HasForeignKey("ClientTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADONETDemoFramework.Models.Waiter", "Waiter")
                        .WithMany("ClientTableWaiters")
                        .HasForeignKey("WaiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTable");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("ADONETDemoFramework.Models.Order", b =>
                {
                    b.HasOne("ADONETDemoFramework.Models.ClientTable", "ClientTable")
                        .WithMany()
                        .HasForeignKey("ClientTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTable");
                });

            modelBuilder.Entity("ADONETDemoFramework.Models.OrderItem", b =>
                {
                    b.HasOne("ADONETDemoFramework.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemName", "FoodItemId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("ADONETDemoFramework.Models.Waiter", b =>
                {
                    b.Navigation("ClientTableWaiters");
                });
#pragma warning restore 612, 618
        }
    }
}
